name: Automated Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ * ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Splunk appinspect Check:
    id: splunk_appinspect_check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            privateApps/**
      - name: Identify Private Apps with Changes in git
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          mkdir -p /tmp/privateApps
          export appsToVet=$(for modifiedFile in ${{ steps.changed-files.outputs.all_modified_files }};do echo ${modifiedFile}|grep "privateApps"| awk -F\/ '{print $2}';done| uniq)
          for app in ${appsToVet} 
          do
            cp -rp privateApps/${app} /tmp/privateApps
          done
          echo "---"
          ls -l /tmp/privateApps
      - name: Check for local directories
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') }}
        run: |
          if [[ $(find /tmp/appPackages -type d -name local | wc -l) -gt 0 ]]
          then
            echo "Local Directories Present"
            exit 1
          fi
      - name: Package Apps for validation
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') }}
        run: |
          mkdir -p /tmp/privatePackages
          cd /tmp/privateApps
          for app in $(find . -type d -maxdepth 1 | sed 's/[\.\/]+//g'| tail -n +2)
          do
            # <TO DO> this section still runs even if no apps need packaging for validation, will have to fix that
            tar -zcf /tmp/privatePackages/${app}_$(cat ${app}/default/app.conf| grep version | sed 's/[a-z\=\. ]//g').tgz ${app}
          done
      - name: Create matrix of apps for inspection
        id: create-matrix-app-inspection
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') }}
        run: |
          find /tmp/privatePackages -type f | egrep "\.tgz$"
  AppInspect: